### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by agramfort** [comment]
@deepcharles have a look to fix the error in a new PR

**Comment by deepcharles** [comment]
solved in #3

**Comment by agramfort** [comment]
can you see how to make travis happy
https://travis-ci.org/github/ramp-kits/human-locomotion ?

>

**Comment by deepcharles** [comment]
There seems to be a mix-up between [travis-ci.org](https://travis-ci.org/) and [travis-ci.com](https://travis-ci.com/) (see this [stackexchange question](https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com) for the difference).
Here are two screenshots of this very repo on each travis-ci website.

image

image

**Comment by agramfort** [comment]
I clicked on the linked in the readme. readme should be fixed then

**Comment by deepcharles** [comment]
Fixed in #4

**Comment by agramfort** [comment]
thx

>

**Pull request merged**
